"""add company to users

Revision ID: 5c371b0dde12
Revises: 6cf60602e1b0
Create Date: 2026-08-22 02:59:58.283066

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "5c371b0dde12"
down_revision: Union[str, Sequence[str], None] = "6cf60602e1b0"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("company_id", sa.UUID(), nullable=True))
    op.create_foreign_key(
        op.f("fk_users_company_id_companies"),
        "users",
        "companies",
        ["company_id"],
        ["id"],
        ondelete="SET NULL",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("fk_users_company_id_companies"), "users", type_="foreignkey"
    )
    op.drop_column("users", "company_id")
    # ### end Alembic commands ###
